### ISSUE TITLE
Botaway blocking the routes

### ISSUE THREAD

**Issue by maxking** [sinisterchipmunk/bot-away#3] opened 2012-04-16 19:48 UTC
I tried this gem and then i was unable to visit the form page even on my rails application. Everything was working fine before that. Can you help?

**Comment by sinisterchipmunk** [comment] 2012-04-17 11:08
What Rails version are you using? Also, are you using any other gems that are not Rails dependencies?

**Comment by sinisterchipmunk** [comment] 2012-04-17 11:10
Even better, if you can create a simple, bare-bones app that reproduces the issue and throw it up to Github, it'd give me a starting point to try to reproduce on my own machine. Also, which Ruby (1.8, 1.9, etc)?

**Comment by maxking** [comment] 2012-04-17 12:17
I am using ruby 1.9 and rails 3.1.1. No i not using other gems too. I will let you know as soon as i put up the base-bones app with same problem.

**Comment by sinisterchipmunk** [comment] 2012-04-29 21:49
Sorry, I can't reproduce this in a test app. Here is how I tested:

```
rvm use --create 1.9.2@rails-3.1.1
gem install rails -v=3.1.1
rails new ba-test
cd ba-test
echo "gem 'bot-away'" >>Gemfile
bundle install
rails g scaffold user name:string
rake db:migrate
rails server
```

Then I visited the page using Chrome. It created and updated the users as expected. I also altered the honeypots via Chrome's "Inspect Element" option; changes with filled honeypots were rejected as expected.

Make sure you're using the latest bot-away gem. If so, can you provide additional information to help track this issue down?

**Comment by sinisterchipmunk** [comment] 2013-11-08 15:46
closing due to lack of input

**Closed as completed by sinisterchipmunk** 2013-11-08 15:46 UTC
