### ISSUE TITLE
Select tag options untainted

### ISSUE THREAD

**Issue by itschn** [sinisterchipmunk/bot-away#1] opened 2011-09-02 15:47 UTC
Here's a patch

```
def content_tag_with_obfuscation(name, content_or_options_with_block = nil, options = nil, *args, &block)
  if block_given?
    content_tag_without_obfuscation(name, content_or_options_with_block, options, *args, &block)
  else
    # this should cover all Rails selects.
    if spinner && options && (options.keys.include?('id') || options.keys.include?('name'))
      if name == 'select' && !content_or_options_with_block.empty?
        # PATCH: add a html safe string
        content = '<option selected value=""></option>'.html_safe
      else
        content = ""
      end
      disguise(content_tag_without_obfuscation(name, content, honeypot_options(options), *args)) +
              content_tag_without_obfuscation(name, content_or_options_with_block, obfuscate_options(options), *args)
    else
      content_tag_without_obfuscation(name, content_or_options_with_block, options, *args)
    end
  end
end
```

**Comment by sinisterchipmunk** [comment] 2011-09-10 20:36
Thanks for this. I'm not ignoring it, just trying to bring the code base up to date first.

**Comment by haraldkrischner** [comment] 2011-12-06 13:05
I guess the problem is the same when I use the text_area formhelper? 

Looking forward to a fix to this content_tag stuff, thanks

**Comment by sinisterchipmunk** [comment] 2012-01-13 12:05
Sorry for the delays here. I've finally gotten the spec suite up to date, so I can test properly under Rails 3. Now rewriting all the old specs (unfortunately, they were pretty tightly coupled to Rails 2.x), and once they're green I hope to close this issue and put out a new release.

**Closed as completed** 2012-01-13 15:38 UTC
